{% set version = "0.4.4" %}

package:
  name: vega
  version: {{ version }}

source:
  fn: vega-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/v/vega/vega-{{ version }}.tar.gz
  md5: f0a60403f5d5384472c5153d53d4d211

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - notebook >=4.2

  run:
    - python
    - ipython
    - notebook >=4.2

test:
  imports:
    - vega

about:
  home: https://github.com/vega/ipyvega
  license: BSD-3-Clause
  summary: 'An IPython/Jupyter widget for Vega and Vega-Lite'

extra:
  recipe-maintainers:
    - jakevdp
    - ellisonbg
    - domoritz
